# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    # Set at least above 200 Hz for effort command interface.
    update_rate: 200  # Hz 

    panda_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    panda_hand_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    force_torque_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    admittance_controller:
      type: admittance_controller/AdmittanceController


panda_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    command_joints:
      - admittance_controller/panda_joint1
      - admittance_controller/panda_joint2
      - admittance_controller/panda_joint3
      - admittance_controller/panda_joint4
      - admittance_controller/panda_joint5
      - admittance_controller/panda_joint6
      - admittance_controller/panda_joint7
    constraints:
      panda_joint1:
        goal: 0.03
        trajectory: 0.5
      panda_joint2:
        goal: 0.03
        trajectory: 0.5
      panda_joint3:
        goal: 0.03
        trajectory: 0.5
      panda_joint4:
        goal: 0.03
        trajectory: 0.5
      panda_joint5:
        goal: 0.03
        trajectory: 0.5
      panda_joint6:
        goal: 0.03
        trajectory: 0.5
      panda_joint7:
        goal: 0.03
        trajectory: 0.5

panda_hand_controller:
  ros__parameters:
    joint: panda_finger_joint1

force_torque_broadcaster:
  ros__parameters:
    frame_id: sensor_fts
    sensor_name: sensor_fts

admittance_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
    
    chainable_command_interfaces:
      - position
      - velocity
    
    kinematics:
      plugin_name: kinematics_interface_kdl/KinematicsInterfaceKDL
      plugin_package: kinematics_interface
      base: panda_link0  # Assumed to be stationary
      tip: sensor_fts  # Use the FT frame as kinematic tip
      alpha: 0.05
    
    ft_sensor:
      name: sensor_fts
      frame:
        id: sensor_fts  # Wrench measurements are in this frame
      filter_coefficient: 0.1
      dead_zone:
        # Small thresholds for [fx, fy, fz, tx, ty, tz]
        # Values below these are treated as zero.
        - 0.0   # x [N]
        - 0.0   # y [N]
        - 0.0   # z [N]
        - 0.0   # rx [N·m]
        - 0.0   # ry [N·m]
        - 0.0   # rz [N·m]
    
    control:
      frame:
        id: panda_hand  # Admittance calcs (displacement etc) are done in this frame. Usually the tool or end-effector
        external: false # control frame exists within URDF kinematic chain
    
    fixed_world_frame:
      frame:            # Gravity points down (neg. Z) in this frame (Usually: world or base_link)
        id: panda_link0
        external: false # control frame exists within URDF kinematic chain
    
    gravity_compensation:
      frame:
        id: panda_hand
      CoG:  # specifies the center of gravity of the end effector
        pos:
          - -0.0096  # x
          - 0.0  # y
          - 0.0311  # z
        force: 7.456  # 0.76 * 9.8065
    
    admittance:
      selected_axes: # true/false: enable/disable admittance on specific axes
        - false  # x
        - false  # y
        - false  # z
        - true  # rx
        - true  # ry
        - true  # rz
    
      # Having ".0" at the end is MUST, otherwise there is a loading error
      # F = M*a + D*v + S*(x - x_d)
      mass:
        - 20.0  # x
        - 20.0  # y
        - 20.0  # z
        - 1.2  # rx
        - 1.2  # ry
        - 1.2  # rz
    
      damping_ratio: # damping can be used instead: zeta = D / (2 * sqrt( M * S ))
        - 2.5 # x
        - 2.5 # y
        - 2.5 # z
        - 2.5 # rx
        - 4.5 # ry
        - 2.5 # rz

      stiffness:
        - 500.0
        - 500.0
        - 500.0
        - 10.0
        - 20.0
        - 10.0

    # general settings
    enable_parameter_update_without_reactivation: true
