# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    # Set at least above 200 Hz for effort command interface.
    update_rate: 100  # Hz 

    panda_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    panda_hand_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    robot_state_broadcaster:
      type: delta_arm_controllers/RobotStateBroadcaster

    servo_controller:
      type: delta_arm_controllers/ServoController
    
    force_torque_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    admittance_controller:
      type: admittance_controller/AdmittanceController


panda_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    command_joints:
      - admittance_controller/panda_joint1
      - admittance_controller/panda_joint2
      - admittance_controller/panda_joint3
      - admittance_controller/panda_joint4
      - admittance_controller/panda_joint5
      - admittance_controller/panda_joint6
      - admittance_controller/panda_joint7
    constraints:
      panda_joint1:
        goal: 0.03
        trajectory: 0.5
      panda_joint2:
        goal: 0.03
        trajectory: 0.5
      panda_joint3:
        goal: 0.03
        trajectory: 0.5
      panda_joint4:
        goal: 0.03
        trajectory: 0.5
      panda_joint5:
        goal: 0.03
        trajectory: 0.5
      panda_joint6:
        goal: 0.03
        trajectory: 0.5
      panda_joint7:
        goal: 0.03
        trajectory: 0.5

panda_hand_controller:
  ros__parameters:
    joint: panda_finger_joint1

robot_state_broadcaster:
  ros__parameters:
    chain_names:
      - panda_arm
    chains:
      tool_tip:
        root: panda_link0
        tip: panda_link8

servo_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    command_joints:
      - admittance_controller/panda_joint1
      - admittance_controller/panda_joint2
      - admittance_controller/panda_joint3
      - admittance_controller/panda_joint4
      - admittance_controller/panda_joint5
      - admittance_controller/panda_joint6
      - admittance_controller/panda_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    # publish_period: 0.02 // Using update rate instead
    default_cmd_type: "twist"  ## twist pose joint_jog
    ## Properties of incoming commands
    command_in_type: "speed_units" # "unitless"> in the range [-1:1], as if from joystick. "speed_units"> cmds are in m/s and rad/s
    scale:
      # Scale parameters are only used if command_in_type=="unitless"
      linear:  1.0  # Max linear velocity. Meters per publish_period. Unit is [m/s]. Only used for Cartesian commands.
      rotational:  3.0 # Max angular velocity. Rads per publish_period. Unit is [rad/s]. Only used for Cartesian commands.
      # Max joint angular/linear velocity. Rads or Meters per publish period. Only used for joint commands on joint_command_in_topic.
      joint: 2.0

    ## Plugins for smoothing outgoing commands
    use_smoothing: true
    smoothing_filter_plugin_name: "online_signal_smoothing::ButterworthFilterPlugin"
    butterworth_filter_coeff: 20.0

    # If is_primary_planning_scene_monitor is set to true, the Servo server's PlanningScene advertises the /get_planning_scene service,
    # which other nodes can use as a source for information about the planning environment.
    # NOTE: If a different node in your system is responsible for the "primary" planning scene instance (e.g. the MoveGroup node),
    # then is_primary_planning_scene_monitor needs to be set to false.
    is_primary_planning_scene_monitor: false

    ## MoveIt properties
    move_group_name:  panda_arm  # (see srdf.xacro file) often 'manipulator' or 'arm'
    planning_frame: panda_link0  # The MoveIt planning frame. Often 'base_link' or 'world'

    ## Stopping behaviour
    incoming_command_timeout:  0.1  # Stop servoing if X seconds elapse without a new command

    ## Configure handling of singularities and joint limits
    lower_singularity_threshold: 50.0  # Start decelerating when the condition number hits this (close to singularity)
    hard_stop_singularity_threshold: 200.0 # Stop when the condition number hits this
    leaving_singularity_threshold_multiplier: 2.0 # Multiply the hard stop limit by this when leaving singularity (see https://github.com/moveit/moveit2/pull/620)

    joint_limit_margin: 0.1 # added as a buffer to joint limits [radians]. If moving quickly, make this larger.
    joint_limit_margins: [0.1]

    ## Topic names
    cartesian_command_in_topic: ~/delta_twist_cmds  # Topic for incoming Cartesian twist commands
    joint_command_in_topic: ~/delta_joint_cmds # Topic for incoming joint angle commands
    pose_command_in_topic: ~/pose_target_cmds
    joint_topic: /joint_states
    status_topic: ~/status # Publish status to this topic

    ## Collision checking for the entire robot body
    check_collisions: true # Check collisions?
    collision_monitor_type: time_based # time_based or distance_based
    collision_check_rate: 20.0 # [Hz] Collision-checking can easily bog down a CPU if done too often.

    # distance_based params
    self_collision_proximity_threshold: 0.03 # Start decelerating when a self-collision is this far [m]
    scene_collision_proximity_threshold: 0.05 # Start decelerating when a scene collision is this far [m]
    # time_based params
    checking_time_period: 0.1 # seconds
    joint_max_checking_offsets: [0.01, 0.01, 0.03, 0.06, 0.06, 0.06, 0.06]


force_torque_broadcaster:
  ros__parameters:
    frame_id: sensor_fts
    sensor_name: sensor_fts

admittance_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
    
    chainable_command_interfaces:
      - position
      - velocity
    
    kinematics:
      plugin_name: kinematics_interface_kdl/KinematicsInterfaceKDL
      plugin_package: kinematics_interface
      base: panda_link0  # Assumed to be stationary
      tip: sensor_fts  # Use the FT frame as kinematic tip
      alpha: 0.05
    
    ft_sensor:
      name: sensor_fts
      frame:
        id: sensor_fts  # Wrench measurements are in this frame
      filter_coefficient: 0.1
      dead_zone:
        # Small thresholds for [fx, fy, fz, tx, ty, tz]
        # Values below these are treated as zero.
        - 0.0   # x [N]
        - 0.0   # y [N]
        - 0.0   # z [N]
        - 0.0   # rx [N·m]
        - 0.0   # ry [N·m]
        - 0.0   # rz [N·m]
    
    control:
      frame:
        id: sensor_fts  # Admittance calcs (displacement etc) are done in this frame. Usually the tool or end-effector
        external: false # control frame exists within URDF kinematic chain
    
    fixed_world_frame:
      frame:            # Gravity points down (neg. Z) in this frame (Usually: world or base_link)
        id: panda_link0
        external: false # control frame exists within URDF kinematic chain
    
    gravity_compensation:
      frame:
        id: sensor_fts
      CoG:  # specifies the center of gravity of the end effector
        pos:
          - -0.0096  # x
          - 0.0  # y
          - 0.0311  # z
        force: 7.456  # 0.76 * 9.8065
    
    admittance:
      selected_axes: # true/false: enable/disable admittance on specific axes
        # - false  # x
        # - false  # y
        # - false  # z
        # - false  # rx
        # - false  # ry
        # - false  # rz

        - true  # x
        - true  # y
        - true  # z
        - true  # rx
        - true  # ry
        - true  # rz

        # - true  # x
        # - true  # y
        # - true  # z
        # - false  # rx
        # - false  # ry
        # - false  # rz

        # - false  # x
        # - false  # y
        # - false  # z
        # - true  # rx
        # - true  # ry
        # - true  # rz
    
      # Having ".0" at the end is MUST, otherwise there is a loading error
      # F = M*a + D*v + S*(x - x_d)
      mass:
        - 20.0  # x
        - 20.0  # y
        - 20.0  # z
        - 1.2  # rx
        - 1.2  # ry
        - 1.2  # rz
    
      damping_ratio: # damping can be used instead: zeta = D / (2 * sqrt( M * S ))
        - 2.5 # x
        - 2.5 # y
        - 2.5 # z
        - 2.5 # rx
        - 4.5 # ry
        - 2.5 # rz

      stiffness:
        - 500.0
        - 500.0
        - 500.0
        - 10.0
        - 20.0
        - 10.0

    # general settings
    enable_parameter_update_without_reactivation: true
